### ISSUE TITLE
Display information about merge requests already voted/reviewed

### ISSUE THREAD

**Issue by nclsHart** [Hexanet/MergeRequestsCI#10]
It could be really useful to have a way to know which PR we have already voted/reviewed.

**Comment by ghost** [comment]
It's a feature I asked @notFloran today but as he said, we have to keep in mind that it could be diplayed on a screen and not be using a "user token".

But I agree that it would be very useful and even more if the counter in the favicon is taking care of this filter.

**Comment by nclsHart** [comment]
Yes, but we must find a way to provide the best user experience in this two use cases : user/personal and screen/dashboard.

Why not introducing a new idea in order to handle this two use cases : something like a "mode". 

Each mode (user or screen) could have their own features and styles. For example : 

User : 
- tokens are considered as user token
- this feature could be added
- more details
- ...

Screen : 
- bigger font size
- less details
- ...

**Comment by notFloran** [comment]
My comment was mostly related to the fact that our user token have access to a lot of projects unlike Jenkins token who has access only to "good" projects.

Example : @nclsHart and me have access to all projects of the team on GitLab.

To avoid unnecessary queries we have to disable "merge request" on projects not use them.

@nclsHart I like the idea of "mode" : with the user mode we can add this feature, merge from MergeRequestCI and a lot of others features.

**Comment by notFloran** [comment]
To move forward on this issue, we need to decide how to display that information in the actual UI.

Any idea @nclsHart @martin-damien ?

**Comment by ghost** [comment]
In fact the most import is not who voted but "Have I voted?".

So a simple column with :+1:  or :-1:  (or nothing if no vote) would be a useful remainder.

**Comment by notFloran** [comment]
@nclsHart Damien's proposal is ok for you?

**Comment by nclsHart** [comment]
@martin-damien @notFloran Yes but it could be also useful to keep the same color scheme in addition with the emoji.

**Comment by notFloran** [comment]
Ok, I will do that.
