### ISSUE TITLE
8.14.0 broke the "have I voted" icon

### ISSUE THREAD

**Issue by ghost** [Hexanet/MergeRequestsCI#103]
![capture d ecran 2016-11-23 a 11 54 22](https://cloud.githubusercontent.com/assets/295478/20559167/a37cd5f2-b173-11e6-8330-a289484b1a11.png)

I upvoted on the fourth MR and the thumbup is not displayed anymore.

**Comment by notFloran** [comment]
![capture d ecran 2016-11-23 a 14 34 43](https://cloud.githubusercontent.com/assets/523981/20563790/5f106be2-b18a-11e6-9cec-edc9aa9b3d38.png)


No problem for me

**Comment by ghost** [comment]
I haven't the problem anymore...
