### ISSUE TITLE
Make the application available through NPM

### ISSUE THREAD

**Issue by ghost** [Hexanet/MergeRequestsCI#13]
Maybe we could provide the application through NPM?

**Comment by notFloran** [comment]
The application is now available on https://hexanet.gitlab.io/MergeRequestsCI/, I think it is no longer useful to do that.

What do you think @martin-damien @nclsHart ?

**Comment by ghost** [comment]
Having it on Gitlab or deploying it by your own is not the same thing.
I could understand if someone doesn't want to use the online version.

For those people, cloning is a way to do, but as the application is based on JS tools, I still think that proposing a NPM package could be useful.

**Comment by notFloran** [comment]
The application doesn't needs JS tools to be used, the application is just a set of html/js/css files.
Before we need JS tools because the config was injected during the build.

**Comment by ghost** [comment]
So, maybe providing a link to the master archive?
This could be done when we'll release the website of the web team.

Is it ok for you?

**Comment by notFloran** [comment]
@martin-damien Ok for me.

We could use the release system of GitHub and add the archive to each release.
