### ISSUE TITLE
Branch column cannot be hidden

### ISSUE THREAD

**Issue by nclsHart** [Hexanet/MergeRequestsCI#139]
#### Description

Since the latest update, the branch column cannot be hidden anymore.

#### How to reproduce

1. Go to the settings page 
2. Set _Display the "Branch" column_ to "no"
3. The Branch column is visible
4. Go back to the settings page
5. The _Display the "Branch" column_ is set to "yes".

**Comment by notFloran** [comment]
![shame](https://user-images.githubusercontent.com/523981/32774203-d53bee40-c92b-11e7-82bb-743d4b1eab72.gif)
