### ISSUE TITLE
Hosted version is outdated

### ISSUE THREAD

**Issue by notFloran** [Hexanet/MergeRequestsCI#146]
The demo hosted with gitlab pages is outdated: it doesn't include the last commits.

The mirroring between github and gitlab is broken:

<img width="744" alt="capture d ecran 2018-05-04 a 19 23 31" src="https://user-images.githubusercontent.com/523981/39642081-b9734cea-4fd0-11e8-91b4-38ba5c161ee2.png">

**Comment by notFloran** [comment]
Any news on that ?

**Comment by ghost** [comment]
Haven't had much time to look at this.

We'll take a look as soon as possible.

**Comment by ghost** [comment]
It seems the mirror used your account @notFloran .

I just changed it to mine. Synchronisation is scheduled.

**Comment by ghost** [comment]
It's ok :)
