### ISSUE TITLE
Hosted version is down

### ISSUE THREAD

**Issue by notFloran** [Hexanet/MergeRequestsCI#150]
The hosted version is down, I get a 404 : https://hexanet.gitlab.io/MergeRequestsCI

A pipeline was run 6 hours ago, maybe something fails : https://gitlab.com/hexanet/MergeRequestsCI/pipelines/27506311

**Comment by ghost** [comment]
I know, the Gitlab page gone away yesterday morning at least.

I re-runed the deployment but nothing changed.

I have to take a look.

**Comment by notFloran** [comment]
Temporary solution, use the artifact from the CI : https://hexanet.gitlab.io/-/MergeRequestsCI/-/jobs/106545835/artifacts/public/index.html#!/

**Comment by ghost** [comment]
It came back. Did nothing…
