### ISSUE TITLE
Link to the CI build

### ISSUE THREAD

**Issue by notFloran** [Hexanet/MergeRequestsCI#27]
With the commit API, we can get the link to the CI build but we need to make an extra request per merge request to the API.

Do you think this is useful?

**Comment by ghost** [comment]
Only if the CI is "failed" I think.

**Comment by nclsHart** [comment]
@martin-damien :+1: 

Only when the CI failed is a great idea.

**Comment by notFloran** [comment]
Ok, I will implement it.

**Comment by nclsHart** [comment]
Done. 

See #37.
