### ISSUE TITLE
Release first stable version

### ISSUE THREAD

**Issue by nclsHart** [Hexanet/MergeRequestsCI#42]
As announced on [GitLab roadmap](https://about.gitlab.com/direction), the next version (8.5) is planned for February 22nd.

Should we try to release a first stable version compatible with GitLab 8.4 before the launch of the 8.5 version?

**Comment by nclsHart** [comment]
Milestone available [here](https://github.com/Hexanet/MergeRequestsCI/milestones/v1.0).

There is particular issues/features that you want to see in this first release?

**Comment by notFloran** [comment]
I think we have a pretty stable code for a first version. I just adds #32 for the v1.0 

The current version seems compatible with 8.4 and 8.5 of GitLab.

**Comment by ghost** [comment]
Shouldn't we have tests before releasing a 1.0?

We should look at npm deployment too I think. It would be great to install it and get updates with `npm install merge-request-ci` for stable releases. (Could we install it as a service, so it would run at startup?)

And of course it will give us a number of installations :)

**Comment by notFloran** [comment]
Todo for the first release : 
- [ ] Add archive to the release. See #13
- [ ] Post on the blog ?
- [ ] Test MRCI with GitLab 8.4

**Comment by notFloran** [comment]
@martin-damien @nclsHart you are ok to release the 1.0 ?

**Comment by nclsHart** [comment]
@notFloran Yep, "allons-y"! :)

**Comment by ghost** [comment]
@notFloran Yep

**Comment by nclsHart** [comment]
Done.

https://github.com/Hexanet/MergeRequestsCI/releases/tag/v1.0.0
