### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by notFloran** [Hexanet/MergeRequestsCI#64]
GitLab use timezone configured in the /etc/gitlab/gitlab.rb, the default value us "UTC".

We have to find a way to format date with the correct timezone.

**Comment by notFloran** [comment]
I've updated the GitLab configuration with the right timezone, since I feel that the correct dates are displayed.

What do you think @nclsHart @martin-damien ?

**Comment by nclsHart** [comment]
It seems to be fixed.
