### ISSUE TITLE
Mergeability label

### ISSUE THREAD

**Issue by nclsHart** [Hexanet/MergeRequestsCI#73]
# Idea

Add a new label next to the CI label indicating the mergeability of a MR.
#  Mergeability

How to define the mergeability of a MR? This could be calculated using the following rules:
- upvote of the assigned user
- CI OK
- more than x upvote

I think this rules should be configurable through the settings tab.

**Comment by notFloran** [comment]
I like the idea but for "more than x upvote" : I don't know if a global setting is the right thing to do, this variables change for each project.

But I don't have a solution to this "problem".
