### ISSUE TITLE
Reduce API calls

### ISSUE THREAD

**Issue by notFloran** [Hexanet/MergeRequestsCI#74]
GitLab API offers a **open_issues_count** property for project API : a **open_merge_requests_count** property would be very useful for us because it will avoid to make an extra API call per projet to check if there are merge requests.

At first glance this change should not be complicated to do : or we create an issue or looking to implement it ourselves and submit a merge request :)

**Comment by nclsHart** [comment]
👍 

Reducing API calls number and so improving performance must be our first goal for the coming releases.

**Comment by notFloran** [comment]
With GitLab 9.5 a new API is available to list all merge requests the authenticated user has access to.

See https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests

**Comment by notFloran** [comment]
After this issue, I think we can release the 2.0. 

What do you think @nclsHart ?

**Comment by nclsHart** [comment]
Yes, everything seems ready for releasing 2.0.

There is still #126 but I don't know if we should consider it for version 2.0.
