### ISSUE TITLE
Display number of items in the title

### ISSUE THREAD

**Issue by ghost** [Hexanet/MergeRequestsCI#92]
[Rambox](http://rambox.pro/) seems to use the number in the page title to display the number of items :

![capture d ecran 2016-08-05 a 16 41 50](https://cloud.githubusercontent.com/assets/295478/17440208/f1c2d6e2-5b2b-11e6-8058-78dac141399f.png)

So, could we add this number (in parenthesis) in the page title (maybe on option saved in the browser) ?

**Comment by notFloran** [comment]
@martin-damien Can you check if my PR fixed your "bug" with Rambox ?

**Comment by ghost** [comment]
Yes it does. Thanks.
